spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #  \u6307\u5B9A\u76F8\u5E94\u63A5\u53E3\u5BF9\u5E94\u7684xml\u6587\u4EF6\u6240\u5728\u76EE\u5F55
  mapper-locations: classpath:mapper/*.xml
  #  \u5B9E\u4F53\u7C7B\u6240\u5728\u5305
  type-aliases-package: com.qzk.mybatis.entity
  configuration:
    # mybatis\u5F00\u542F\u9A7C\u5CF0\u5F0F\u547D\u540D
    map-underscore-to-camel-case: true