server:
  port: 8080
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: beans,env,info,health,customEndpoint
#        exclude: mappings



spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        instance:
          service-base-url: http://localhost:8080
          name: "\u6D4B\u8BD5\u5E94\u7528\u6CE8\u518C"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'